// Description: **Sayagata** — Sayagata (紗綾形)
// Sayagata (紗綾形) Sashiko Template
// Interlocking 卍 (manji-tsunagi / linked manji). The manji centres sit on a
// square lattice rotated ~18° (generated by v1 and its 90° rotation) so the
// hooks reach toward each other and weave, instead of fusing into a plain
// cross-grid. Cut full-thickness.
//
// A lone 卍 is a tree (a + with four dangling L-hooks) and encloses nothing; the
// ONLY closed loops in the whole pattern come from neighbouring hooks meeting
// end-to-end, which traps a solid island in each loop. So each hook is drawn a
// hair short of its meeting point (hook_gap) — the same corner-gap trick kikko
// uses at its vertices — which breaks every loop and keeps the plate one piece.

use <sashiko_lib.scad>
include <sashiko_config.scad>

unit      = 3;    // stroke spacing — pattern scale (mm); arm = unit, hook = 2*unit
hook_gap  = 1.4;  // solid tab left where two hooks meet (mm) — keeps plate joined

A  = unit;        // arm half-length (centre to hook bend)
Hh = 2 * unit;    // hook length
r  = groove_w / 2;

v1 = [A + Hh, Hh - A];      // (3,1)*unit — nearest-neighbour lattice vector
v2 = [-(Hh - A), A + Hh];   // (-1,3)*unit — 90° rotation of v1

// One 卍 centred at (cx,cy): a + cross with each arm hooked counter-clockwise.
// Hooks stop hook_gap short of their free ends so they never close a loop.
module manji(cx, cy) {
    g = hook_gap;
    slot_dash([cx, cy-A], [cx, cy+A], r);              // vertical bar
    slot_dash([cx-A, cy], [cx+A, cy], r);              // horizontal bar
    slot_dash([cx, cy+A], [cx - Hh + g, cy+A], r);     // top hook   (turns -x)
    slot_dash([cx+A, cy], [cx+A, cy + Hh - g], r);     // right hook  (turns +y)
    slot_dash([cx, cy-A], [cx + Hh - g, cy-A], r);     // bottom hook (turns +x)
    slot_dash([cx-A, cy], [cx-A, cy - Hh + g], r);     // left hook   (turns -y)
}

// Cover the plate's half-diagonal in lattice steps (|v1| = unit*sqrt(10)).
N = ceil(sqrt(plate_w*plate_w + plate_h*plate_h) / 2 / (unit*sqrt(10))) + 1;

sashiko_plate(plate_w, plate_h, plate_t, border, chamfer, reg)
    for (m = [-N:N]) for (n = [-N:N])
        manji(plate_w/2 + m*v1[0] + n*v2[0],
              plate_h/2 + m*v1[1] + n*v2[1]);
